trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    Node6:
      NODE_VERSION: '6.x'
    Node8:
      NODE_VERSION: '8.x'
    Node10:
      NODE_VERSION: '10.x'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
      checkLatest: true
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies (npm install)'

  - script: npm run test
    displayName: 'Run tests'

